[package]
name = "indiemotion"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
name = "indiemotion"
path = "src/cli/indiemotion.rs"


[workspace]
members = [
  "crates/*",
]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.66"
chrono = "0.4.24"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.28"
indiemotion-api = { path = "crates/indiemotion-api"}
indiemotion-proto = { path = "crates/indiemotion-proto"}
serde_derive = "1.0.160"
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["full"] }
tower-http = { version = "0.3.5", features = ["trace"]}
tokio-stream = { version = "0.1.12", features = ["net", "sync"] }
tonic = "0.9"
tracing = "0.1"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
warp = "0.3.3"
hostname = "0.3.1"

[dev-dependencies]
rstest = "0.17.0"
