
[workspace]
members = [
  "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"


[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.73"
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive"] }
futures = "0.3.28"
indiemotion-api = { path = "crates/indiemotion-api"}
serde = { version = "1.0.188", features = ["derive", "rc"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.4.4", features = ["trace"]}
tokio-stream = { version = "0.1.14", features = ["net", "sync"] }
tracing = "0.1"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
warp = "0.3.5"
hostname = "0.3.1"
derive_more = "0.99.17"
rstest = "0.18.2"
libmdns = "0.7.5"
