[package]
name = "indiemotion"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "inmotion"
path = "src/cli/bin.rs"


[workspace]
members = [
  "crates/*",
]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.60"
chrono = "0.4.23"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.25"
indiemotion-api = { path = "crates/indiemotion-api"}
indiemotion-proto = { path = "crates/indiemotion-proto"}
serde_derive = "1.0.151"
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tower-http = { version = "0.3.5", features = ["trace"]}
tokio-stream = { version = "0.1.12", features = ["net"] }
tonic = "0.8"
tracing = "0.1"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }
warp = "0.3.3"

[dev-dependencies]
rstest = "0.16.0"
