[package]
name = "indiemotion"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "indiemotiond"
path = "src/cli/bin.rs"


[workspace]
members = [
  "crates/*",
]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.60"
clap = { version = "3.1.6", features = ["derive"] }
indiemotion-api = { path = "crates/indiemotion-api"}
serde_derive = "1.0.151"
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
warp = "0.3.3"

[dev-dependencies]
rstest = "0.16.0"
