
[workspace]
members = [
  "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"


[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.66"
chrono = "0.4.24"
clap = { version = "4.3.4", features = ["derive"] }
futures = "0.3.28"
indiemotion-api = { path = "crates/indiemotion-api"}
serde = { version = "1.0.171", features = ["derive", "rc"] }
serde_json = "1.0.97"
thiserror = "1.0.40"
tokio = { version = "1.24.2", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"]}
tokio-stream = { version = "0.1.12", features = ["net", "sync"] }
tracing = "0.1"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
warp = "0.3.3"
hostname = "0.3.1"
derive_more = "0.99.17"
rstest = "0.17.0"
libmdns = "0.7.5"