[package]
name = "cinemotion-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bevy_ecs = "0.13.2"
derive_more.workspace = true
thiserror.workspace = true
tokio.workspace = true
