[package]
name = "indiemotion-proto"
version = "0.1.0"
authors = ["Andrew Paxson <paxsonsa@gmail.com>"]
edition = "2021"

[dependencies]
prost = "0.11"
tonic = "0.9"

[build-dependencies]
tonic-build = "0.8"
