[package]
name = "indiemotion-swift"
version.workspace = true
edition.workspace = true

build = "build.rs"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
swift-bridge-build  = "0.1"

[dependencies]
swift-bridge = "0.1"
indiemotion-api.workspace = true