[package]
name = "indiemotion-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
serde = "1.0.151"
serde_derive = "1.0.156"
serde_json = "1.0.91"
thiserror = "1.0.38"
tracing = "0.1.37"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
async-trait = "0.1.60"
indiemotion-proto = { path = "../indiemotion-proto"}

[dev-dependencies]
rstest = "0.16.0"
