# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .payload import v1_pb2 as payload_dot_v1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='indiemotion.protobuf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x14indiemotion.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10payload.v1.proto\"\x86\x01\n\x06Header\x12-\n\ttimestamp\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\x14 \x01(\t\x12\x19\n\x11requires_response\x18\x1e \x01(\x08\x12\x17\n\nresponseId\x18( \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_responseId\"\xec\x06\n\x07Message\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.indiemotion.protobuf.Header\x12\x44\n\x0b\x61\x63knowledge\x18\x14 \x01(\x0b\x32-.indiemotion.protobuf.payloads.v1.AcknowledgeH\x00\x12\x38\n\x05\x65rror\x18\x19 \x01(\x0b\x32\'.indiemotion.protobuf.payloads.v1.ErrorH\x00\x12J\n\x0fget_camera_list\x18\x1e \x01(\x0b\x32/.indiemotion.protobuf.payloads.v1.GetCameraListH\x00\x12\x43\n\x0b\x63\x61mera_list\x18\x1f \x01(\x0b\x32,.indiemotion.protobuf.payloads.v1.CameraListH\x00\x12N\n\x11set_active_camera\x18  \x01(\x0b\x32\x31.indiemotion.protobuf.payloads.v1.SetActiveCameraH\x00\x12J\n\x0fmotion_set_mode\x18( \x01(\x0b\x32/.indiemotion.protobuf.payloads.v1.MotionSetModeH\x00\x12J\n\x0fmotion_get_mode\x18) \x01(\x0b\x32/.indiemotion.protobuf.payloads.v1.MotionGetModeH\x00\x12P\n\x12motion_active_mode\x18* \x01(\x0b\x32\x32.indiemotion.protobuf.payloads.v1.MotionActiveModeH\x00\x12\x45\n\x0cmotion_xform\x18+ \x01(\x0b\x32-.indiemotion.protobuf.payloads.v1.MotionXFormH\x00\x12G\n\rsession_start\x18\x32 \x01(\x0b\x32..indiemotion.protobuf.payloads.v1.SessionStartH\x00\x12M\n\x10session_shutdown\x18\x33 \x01(\x0b\x32\x31.indiemotion.protobuf.payloads.v1.SessionShutdownH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,payload_dot_v1__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='indiemotion.protobuf.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='indiemotion.protobuf.Header.timestamp', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='indiemotion.protobuf.Header.id', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requires_response', full_name='indiemotion.protobuf.Header.requires_response', index=2,
      number=30, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseId', full_name='indiemotion.protobuf.Header.responseId', index=3,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_responseId', full_name='indiemotion.protobuf.Header._responseId',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=92,
  serialized_end=226,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='indiemotion.protobuf.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='indiemotion.protobuf.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acknowledge', full_name='indiemotion.protobuf.Message.acknowledge', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='indiemotion.protobuf.Message.error', index=2,
      number=25, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_camera_list', full_name='indiemotion.protobuf.Message.get_camera_list', index=3,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_list', full_name='indiemotion.protobuf.Message.camera_list', index=4,
      number=31, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_active_camera', full_name='indiemotion.protobuf.Message.set_active_camera', index=5,
      number=32, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_set_mode', full_name='indiemotion.protobuf.Message.motion_set_mode', index=6,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_get_mode', full_name='indiemotion.protobuf.Message.motion_get_mode', index=7,
      number=41, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_active_mode', full_name='indiemotion.protobuf.Message.motion_active_mode', index=8,
      number=42, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_xform', full_name='indiemotion.protobuf.Message.motion_xform', index=9,
      number=43, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_start', full_name='indiemotion.protobuf.Message.session_start', index=10,
      number=50, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_shutdown', full_name='indiemotion.protobuf.Message.session_shutdown', index=11,
      number=51, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='indiemotion.protobuf.Message.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=229,
  serialized_end=1105,
)

_HEADER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_HEADER.oneofs_by_name['_responseId'].fields.append(
  _HEADER.fields_by_name['responseId'])
_HEADER.fields_by_name['responseId'].containing_oneof = _HEADER.oneofs_by_name['_responseId']
_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['acknowledge'].message_type = payload_dot_v1__pb2._ACKNOWLEDGE
_MESSAGE.fields_by_name['error'].message_type = payload_dot_v1__pb2._ERROR
_MESSAGE.fields_by_name['get_camera_list'].message_type = payload_dot_v1__pb2._GETCAMERALIST
_MESSAGE.fields_by_name['camera_list'].message_type = payload_dot_v1__pb2._CAMERALIST
_MESSAGE.fields_by_name['set_active_camera'].message_type = payload_dot_v1__pb2._SETACTIVECAMERA
_MESSAGE.fields_by_name['motion_set_mode'].message_type = payload_dot_v1__pb2._MOTIONSETMODE
_MESSAGE.fields_by_name['motion_get_mode'].message_type = payload_dot_v1__pb2._MOTIONGETMODE
_MESSAGE.fields_by_name['motion_active_mode'].message_type = payload_dot_v1__pb2._MOTIONACTIVEMODE
_MESSAGE.fields_by_name['motion_xform'].message_type = payload_dot_v1__pb2._MOTIONXFORM
_MESSAGE.fields_by_name['session_start'].message_type = payload_dot_v1__pb2._SESSIONSTART
_MESSAGE.fields_by_name['session_shutdown'].message_type = payload_dot_v1__pb2._SESSIONSHUTDOWN
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['acknowledge'])
_MESSAGE.fields_by_name['acknowledge'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['error'])
_MESSAGE.fields_by_name['error'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['get_camera_list'])
_MESSAGE.fields_by_name['get_camera_list'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['camera_list'])
_MESSAGE.fields_by_name['camera_list'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['set_active_camera'])
_MESSAGE.fields_by_name['set_active_camera'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['motion_set_mode'])
_MESSAGE.fields_by_name['motion_set_mode'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['motion_get_mode'])
_MESSAGE.fields_by_name['motion_get_mode'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['motion_active_mode'])
_MESSAGE.fields_by_name['motion_active_mode'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['motion_xform'])
_MESSAGE.fields_by_name['motion_xform'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['session_start'])
_MESSAGE.fields_by_name['session_start'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['session_shutdown'])
_MESSAGE.fields_by_name['session_shutdown'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:indiemotion.protobuf.Header)
  })
_sym_db.RegisterMessage(Header)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:indiemotion.protobuf.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
