// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace indiemotionpb {
constexpr Header::Header(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , responseid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct HeaderDefaultTypeInternal {
  constexpr HeaderDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~HeaderDefaultTypeInternal() {}
  union {
    Header _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT HeaderDefaultTypeInternal _Header_default_instance_;
constexpr Message::Message(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : header_(nullptr)
  , _oneof_case_{}{}
struct MessageDefaultTypeInternal {
  constexpr MessageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace indiemotionpb
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_messages_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_messages_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_messages_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Header, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Header, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Header, id_),
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Header, responseid_),
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Message, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Message, header_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::indiemotionpb::Message, payload_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::indiemotionpb::Header)},
  { 9, -1, sizeof(::indiemotionpb::Message)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::indiemotionpb::_Header_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::indiemotionpb::_Message_default_instance_),
};

const char descriptor_table_protodef_messages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016messages.proto\022\rindiemotionpb\032\037google/"
  "protobuf/timestamp.proto\032\016payloads.proto"
  "\"<\n\006Header\022\n\n\002id\030\024 \001(\t\022\027\n\nresponseId\030( \001"
  "(\tH\000\210\001\001B\r\n\013_responseId\"\327\005\n\007Message\022%\n\006he"
  "ader\030\001 \001(\0132\025.indiemotionpb.Header\022:\n\013ack"
  "nowledge\030\024 \001(\0132#.indiemotionpb.payloads."
  "AcknowledgeH\000\022.\n\005error\030\031 \001(\0132\035.indiemoti"
  "onpb.payloads.ErrorH\000\022D\n\021input_device_in"
  "fo\030\036 \001(\0132\'.indiemotionpb.payloads.InputD"
  "eviceInfoH\000\022G\n\022initialize_session\030\037 \001(\0132"
  ").indiemotionpb.payloads.InitializeSessi"
  "onH\000\022C\n\020shutdown_session\030  \001(\0132\'.indiemo"
  "tionpb.payloads.ShutdownSessionH\000\0229\n\013cam"
  "era_list\030( \001(\0132\".indiemotionpb.payloads."
  "CameraListH\000\022@\n\017get_camera_list\030) \001(\0132%."
  "indiemotionpb.payloads.GetCameraListH\000\022C"
  "\n\020session_property\0302 \001(\0132\'.indiemotionpb"
  ".payloads.SessionPropertyH\000\022P\n\024get_sessi"
  "on_property\0303 \001(\01320.indiemotionpb.payloa"
  "ds.GetSessionPropertyByNameH\000\022F\n\022input_d"
  "evice_xform\030< \001(\0132(.indiemotionpb.payloa"
  "ds.InputDeviceXFormH\000B\t\n\007payloadb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_messages_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
  &::descriptor_table_payloads_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_messages_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto = {
  false, false, 880, descriptor_table_protodef_messages_2eproto, "messages.proto", 
  &descriptor_table_messages_2eproto_once, descriptor_table_messages_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_messages_2eproto::offsets,
  file_level_metadata_messages_2eproto, file_level_enum_descriptors_messages_2eproto, file_level_service_descriptors_messages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_messages_2eproto_getter() {
  return &descriptor_table_messages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_messages_2eproto(&descriptor_table_messages_2eproto);
namespace indiemotionpb {

// ===================================================================

class Header::_Internal {
 public:
  using HasBits = decltype(std::declval<Header>()._has_bits_);
  static void set_has_responseid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Header::Header(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:indiemotionpb.Header)
}
Header::Header(const Header& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArenaForAllocation());
  }
  responseid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_responseid()) {
    responseid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_responseid(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:indiemotionpb.Header)
}

inline void Header::SharedCtor() {
id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
responseid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:indiemotionpb.Header)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Header::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  responseid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Header::ArenaDtor(void* object) {
  Header* _this = reinterpret_cast< Header* >(object);
  (void)_this;
}
void Header::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Header::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:indiemotionpb.Header)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmpty();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    responseid_.ClearNonDefaultToEmpty();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Header::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "indiemotionpb.Header.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string responseId = 40;
      case 40:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_responseid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "indiemotionpb.Header.responseId"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Header::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:indiemotionpb.Header)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 20;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "indiemotionpb.Header.id");
    target = stream->WriteStringMaybeAliased(
        20, this->_internal_id(), target);
  }

  // optional string responseId = 40;
  if (_internal_has_responseid()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_responseid().data(), static_cast<int>(this->_internal_responseid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "indiemotionpb.Header.responseId");
    target = stream->WriteStringMaybeAliased(
        40, this->_internal_responseid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:indiemotionpb.Header)
  return target;
}

size_t Header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:indiemotionpb.Header)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 20;
  if (!this->_internal_id().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // optional string responseId = 40;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_responseid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Header::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Header::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Header::GetClassData() const { return &_class_data_; }

void Header::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<Header *>(to)->MergeFrom(
      static_cast<const Header &>(from));
}


void Header::MergeFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:indiemotionpb.Header)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _internal_set_id(from._internal_id());
  }
  if (from._internal_has_responseid()) {
    _internal_set_responseid(from._internal_responseid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:indiemotionpb.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  return true;
}

void Header::InternalSwap(Header* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &id_, GetArenaForAllocation(),
      &other->id_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &responseid_, GetArenaForAllocation(),
      &other->responseid_, other->GetArenaForAllocation()
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Header::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[0]);
}

// ===================================================================

class Message::_Internal {
 public:
  static const ::indiemotionpb::Header& header(const Message* msg);
  static const ::indiemotionpb::payloads::Acknowledge& acknowledge(const Message* msg);
  static const ::indiemotionpb::payloads::Error& error(const Message* msg);
  static const ::indiemotionpb::payloads::InputDeviceInfo& input_device_info(const Message* msg);
  static const ::indiemotionpb::payloads::InitializeSession& initialize_session(const Message* msg);
  static const ::indiemotionpb::payloads::ShutdownSession& shutdown_session(const Message* msg);
  static const ::indiemotionpb::payloads::CameraList& camera_list(const Message* msg);
  static const ::indiemotionpb::payloads::GetCameraList& get_camera_list(const Message* msg);
  static const ::indiemotionpb::payloads::SessionProperty& session_property(const Message* msg);
  static const ::indiemotionpb::payloads::GetSessionPropertyByName& get_session_property(const Message* msg);
  static const ::indiemotionpb::payloads::InputDeviceXForm& input_device_xform(const Message* msg);
};

const ::indiemotionpb::Header&
Message::_Internal::header(const Message* msg) {
  return *msg->header_;
}
const ::indiemotionpb::payloads::Acknowledge&
Message::_Internal::acknowledge(const Message* msg) {
  return *msg->payload_.acknowledge_;
}
const ::indiemotionpb::payloads::Error&
Message::_Internal::error(const Message* msg) {
  return *msg->payload_.error_;
}
const ::indiemotionpb::payloads::InputDeviceInfo&
Message::_Internal::input_device_info(const Message* msg) {
  return *msg->payload_.input_device_info_;
}
const ::indiemotionpb::payloads::InitializeSession&
Message::_Internal::initialize_session(const Message* msg) {
  return *msg->payload_.initialize_session_;
}
const ::indiemotionpb::payloads::ShutdownSession&
Message::_Internal::shutdown_session(const Message* msg) {
  return *msg->payload_.shutdown_session_;
}
const ::indiemotionpb::payloads::CameraList&
Message::_Internal::camera_list(const Message* msg) {
  return *msg->payload_.camera_list_;
}
const ::indiemotionpb::payloads::GetCameraList&
Message::_Internal::get_camera_list(const Message* msg) {
  return *msg->payload_.get_camera_list_;
}
const ::indiemotionpb::payloads::SessionProperty&
Message::_Internal::session_property(const Message* msg) {
  return *msg->payload_.session_property_;
}
const ::indiemotionpb::payloads::GetSessionPropertyByName&
Message::_Internal::get_session_property(const Message* msg) {
  return *msg->payload_.get_session_property_;
}
const ::indiemotionpb::payloads::InputDeviceXForm&
Message::_Internal::input_device_xform(const Message* msg) {
  return *msg->payload_.input_device_xform_;
}
void Message::set_allocated_acknowledge(::indiemotionpb::payloads::Acknowledge* acknowledge) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (acknowledge) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(acknowledge));
    if (message_arena != submessage_arena) {
      acknowledge = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acknowledge, submessage_arena);
    }
    set_has_acknowledge();
    payload_.acknowledge_ = acknowledge;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.acknowledge)
}
void Message::clear_acknowledge() {
  if (_internal_has_acknowledge()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.acknowledge_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_error(::indiemotionpb::payloads::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    payload_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.error)
}
void Message::clear_error() {
  if (_internal_has_error()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.error_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_input_device_info(::indiemotionpb::payloads::InputDeviceInfo* input_device_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (input_device_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input_device_info));
    if (message_arena != submessage_arena) {
      input_device_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input_device_info, submessage_arena);
    }
    set_has_input_device_info();
    payload_.input_device_info_ = input_device_info;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.input_device_info)
}
void Message::clear_input_device_info() {
  if (_internal_has_input_device_info()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.input_device_info_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_initialize_session(::indiemotionpb::payloads::InitializeSession* initialize_session) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (initialize_session) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(initialize_session));
    if (message_arena != submessage_arena) {
      initialize_session = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, initialize_session, submessage_arena);
    }
    set_has_initialize_session();
    payload_.initialize_session_ = initialize_session;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.initialize_session)
}
void Message::clear_initialize_session() {
  if (_internal_has_initialize_session()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.initialize_session_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_shutdown_session(::indiemotionpb::payloads::ShutdownSession* shutdown_session) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (shutdown_session) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(shutdown_session));
    if (message_arena != submessage_arena) {
      shutdown_session = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, shutdown_session, submessage_arena);
    }
    set_has_shutdown_session();
    payload_.shutdown_session_ = shutdown_session;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.shutdown_session)
}
void Message::clear_shutdown_session() {
  if (_internal_has_shutdown_session()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.shutdown_session_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_camera_list(::indiemotionpb::payloads::CameraList* camera_list) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (camera_list) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(camera_list));
    if (message_arena != submessage_arena) {
      camera_list = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, camera_list, submessage_arena);
    }
    set_has_camera_list();
    payload_.camera_list_ = camera_list;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.camera_list)
}
void Message::clear_camera_list() {
  if (_internal_has_camera_list()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.camera_list_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_get_camera_list(::indiemotionpb::payloads::GetCameraList* get_camera_list) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (get_camera_list) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(get_camera_list));
    if (message_arena != submessage_arena) {
      get_camera_list = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, get_camera_list, submessage_arena);
    }
    set_has_get_camera_list();
    payload_.get_camera_list_ = get_camera_list;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.get_camera_list)
}
void Message::clear_get_camera_list() {
  if (_internal_has_get_camera_list()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.get_camera_list_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_session_property(::indiemotionpb::payloads::SessionProperty* session_property) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (session_property) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(session_property));
    if (message_arena != submessage_arena) {
      session_property = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, session_property, submessage_arena);
    }
    set_has_session_property();
    payload_.session_property_ = session_property;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.session_property)
}
void Message::clear_session_property() {
  if (_internal_has_session_property()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.session_property_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_get_session_property(::indiemotionpb::payloads::GetSessionPropertyByName* get_session_property) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (get_session_property) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(get_session_property));
    if (message_arena != submessage_arena) {
      get_session_property = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, get_session_property, submessage_arena);
    }
    set_has_get_session_property();
    payload_.get_session_property_ = get_session_property;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.get_session_property)
}
void Message::clear_get_session_property() {
  if (_internal_has_get_session_property()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.get_session_property_;
    }
    clear_has_payload();
  }
}
void Message::set_allocated_input_device_xform(::indiemotionpb::payloads::InputDeviceXForm* input_device_xform) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (input_device_xform) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input_device_xform));
    if (message_arena != submessage_arena) {
      input_device_xform = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input_device_xform, submessage_arena);
    }
    set_has_input_device_xform();
    payload_.input_device_xform_ = input_device_xform;
  }
  // @@protoc_insertion_point(field_set_allocated:indiemotionpb.Message.input_device_xform)
}
void Message::clear_input_device_xform() {
  if (_internal_has_input_device_xform()) {
    if (GetArenaForAllocation() == nullptr) {
      delete payload_.input_device_xform_;
    }
    clear_has_payload();
  }
}
Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:indiemotionpb.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    header_ = new ::indiemotionpb::Header(*from.header_);
  } else {
    header_ = nullptr;
  }
  clear_has_payload();
  switch (from.payload_case()) {
    case kAcknowledge: {
      _internal_mutable_acknowledge()->::indiemotionpb::payloads::Acknowledge::MergeFrom(from._internal_acknowledge());
      break;
    }
    case kError: {
      _internal_mutable_error()->::indiemotionpb::payloads::Error::MergeFrom(from._internal_error());
      break;
    }
    case kInputDeviceInfo: {
      _internal_mutable_input_device_info()->::indiemotionpb::payloads::InputDeviceInfo::MergeFrom(from._internal_input_device_info());
      break;
    }
    case kInitializeSession: {
      _internal_mutable_initialize_session()->::indiemotionpb::payloads::InitializeSession::MergeFrom(from._internal_initialize_session());
      break;
    }
    case kShutdownSession: {
      _internal_mutable_shutdown_session()->::indiemotionpb::payloads::ShutdownSession::MergeFrom(from._internal_shutdown_session());
      break;
    }
    case kCameraList: {
      _internal_mutable_camera_list()->::indiemotionpb::payloads::CameraList::MergeFrom(from._internal_camera_list());
      break;
    }
    case kGetCameraList: {
      _internal_mutable_get_camera_list()->::indiemotionpb::payloads::GetCameraList::MergeFrom(from._internal_get_camera_list());
      break;
    }
    case kSessionProperty: {
      _internal_mutable_session_property()->::indiemotionpb::payloads::SessionProperty::MergeFrom(from._internal_session_property());
      break;
    }
    case kGetSessionProperty: {
      _internal_mutable_get_session_property()->::indiemotionpb::payloads::GetSessionPropertyByName::MergeFrom(from._internal_get_session_property());
      break;
    }
    case kInputDeviceXform: {
      _internal_mutable_input_device_xform()->::indiemotionpb::payloads::InputDeviceXForm::MergeFrom(from._internal_input_device_xform());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:indiemotionpb.Message)
}

inline void Message::SharedCtor() {
header_ = nullptr;
clear_has_payload();
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:indiemotionpb.Message)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete header_;
  if (has_payload()) {
    clear_payload();
  }
}

void Message::ArenaDtor(void* object) {
  Message* _this = reinterpret_cast< Message* >(object);
  (void)_this;
}
void Message::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Message::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:indiemotionpb.Message)
  switch (payload_case()) {
    case kAcknowledge: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.acknowledge_;
      }
      break;
    }
    case kError: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.error_;
      }
      break;
    }
    case kInputDeviceInfo: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.input_device_info_;
      }
      break;
    }
    case kInitializeSession: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.initialize_session_;
      }
      break;
    }
    case kShutdownSession: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.shutdown_session_;
      }
      break;
    }
    case kCameraList: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.camera_list_;
      }
      break;
    }
    case kGetCameraList: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.get_camera_list_;
      }
      break;
    }
    case kSessionProperty: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.session_property_;
      }
      break;
    }
    case kGetSessionProperty: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.get_session_property_;
      }
      break;
    }
    case kInputDeviceXform: {
      if (GetArenaForAllocation() == nullptr) {
        delete payload_.input_device_xform_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:indiemotionpb.Message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .indiemotionpb.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.Acknowledge acknowledge = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_acknowledge(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.Error error = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 202)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.InputDeviceInfo input_device_info = 30;
      case 30:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 242)) {
          ptr = ctx->ParseMessage(_internal_mutable_input_device_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.InitializeSession initialize_session = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 250)) {
          ptr = ctx->ParseMessage(_internal_mutable_initialize_session(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.ShutdownSession shutdown_session = 32;
      case 32:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 2)) {
          ptr = ctx->ParseMessage(_internal_mutable_shutdown_session(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.CameraList camera_list = 40;
      case 40:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_camera_list(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.GetCameraList get_camera_list = 41;
      case 41:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_get_camera_list(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.SessionProperty session_property = 50;
      case 50:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 146)) {
          ptr = ctx->ParseMessage(_internal_mutable_session_property(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.GetSessionPropertyByName get_session_property = 51;
      case 51:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_get_session_property(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .indiemotionpb.payloads.InputDeviceXForm input_device_xform = 60;
      case 60:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 226)) {
          ptr = ctx->ParseMessage(_internal_mutable_input_device_xform(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Message::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:indiemotionpb.Message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .indiemotionpb.Header header = 1;
  if (this->_internal_has_header()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // .indiemotionpb.payloads.Acknowledge acknowledge = 20;
  if (_internal_has_acknowledge()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        20, _Internal::acknowledge(this), target, stream);
  }

  // .indiemotionpb.payloads.Error error = 25;
  if (_internal_has_error()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        25, _Internal::error(this), target, stream);
  }

  // .indiemotionpb.payloads.InputDeviceInfo input_device_info = 30;
  if (_internal_has_input_device_info()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        30, _Internal::input_device_info(this), target, stream);
  }

  // .indiemotionpb.payloads.InitializeSession initialize_session = 31;
  if (_internal_has_initialize_session()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        31, _Internal::initialize_session(this), target, stream);
  }

  // .indiemotionpb.payloads.ShutdownSession shutdown_session = 32;
  if (_internal_has_shutdown_session()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        32, _Internal::shutdown_session(this), target, stream);
  }

  // .indiemotionpb.payloads.CameraList camera_list = 40;
  if (_internal_has_camera_list()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        40, _Internal::camera_list(this), target, stream);
  }

  // .indiemotionpb.payloads.GetCameraList get_camera_list = 41;
  if (_internal_has_get_camera_list()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        41, _Internal::get_camera_list(this), target, stream);
  }

  // .indiemotionpb.payloads.SessionProperty session_property = 50;
  if (_internal_has_session_property()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        50, _Internal::session_property(this), target, stream);
  }

  // .indiemotionpb.payloads.GetSessionPropertyByName get_session_property = 51;
  if (_internal_has_get_session_property()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        51, _Internal::get_session_property(this), target, stream);
  }

  // .indiemotionpb.payloads.InputDeviceXForm input_device_xform = 60;
  if (_internal_has_input_device_xform()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        60, _Internal::input_device_xform(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:indiemotionpb.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:indiemotionpb.Message)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .indiemotionpb.Header header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *header_);
  }

  switch (payload_case()) {
    // .indiemotionpb.payloads.Acknowledge acknowledge = 20;
    case kAcknowledge: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.acknowledge_);
      break;
    }
    // .indiemotionpb.payloads.Error error = 25;
    case kError: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.error_);
      break;
    }
    // .indiemotionpb.payloads.InputDeviceInfo input_device_info = 30;
    case kInputDeviceInfo: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.input_device_info_);
      break;
    }
    // .indiemotionpb.payloads.InitializeSession initialize_session = 31;
    case kInitializeSession: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.initialize_session_);
      break;
    }
    // .indiemotionpb.payloads.ShutdownSession shutdown_session = 32;
    case kShutdownSession: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.shutdown_session_);
      break;
    }
    // .indiemotionpb.payloads.CameraList camera_list = 40;
    case kCameraList: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.camera_list_);
      break;
    }
    // .indiemotionpb.payloads.GetCameraList get_camera_list = 41;
    case kGetCameraList: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.get_camera_list_);
      break;
    }
    // .indiemotionpb.payloads.SessionProperty session_property = 50;
    case kSessionProperty: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.session_property_);
      break;
    }
    // .indiemotionpb.payloads.GetSessionPropertyByName get_session_property = 51;
    case kGetSessionProperty: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.get_session_property_);
      break;
    }
    // .indiemotionpb.payloads.InputDeviceXForm input_device_xform = 60;
    case kInputDeviceXform: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *payload_.input_device_xform_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }

void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<Message *>(to)->MergeFrom(
      static_cast<const Message &>(from));
}


void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:indiemotionpb.Message)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_header()) {
    _internal_mutable_header()->::indiemotionpb::Header::MergeFrom(from._internal_header());
  }
  switch (from.payload_case()) {
    case kAcknowledge: {
      _internal_mutable_acknowledge()->::indiemotionpb::payloads::Acknowledge::MergeFrom(from._internal_acknowledge());
      break;
    }
    case kError: {
      _internal_mutable_error()->::indiemotionpb::payloads::Error::MergeFrom(from._internal_error());
      break;
    }
    case kInputDeviceInfo: {
      _internal_mutable_input_device_info()->::indiemotionpb::payloads::InputDeviceInfo::MergeFrom(from._internal_input_device_info());
      break;
    }
    case kInitializeSession: {
      _internal_mutable_initialize_session()->::indiemotionpb::payloads::InitializeSession::MergeFrom(from._internal_initialize_session());
      break;
    }
    case kShutdownSession: {
      _internal_mutable_shutdown_session()->::indiemotionpb::payloads::ShutdownSession::MergeFrom(from._internal_shutdown_session());
      break;
    }
    case kCameraList: {
      _internal_mutable_camera_list()->::indiemotionpb::payloads::CameraList::MergeFrom(from._internal_camera_list());
      break;
    }
    case kGetCameraList: {
      _internal_mutable_get_camera_list()->::indiemotionpb::payloads::GetCameraList::MergeFrom(from._internal_get_camera_list());
      break;
    }
    case kSessionProperty: {
      _internal_mutable_session_property()->::indiemotionpb::payloads::SessionProperty::MergeFrom(from._internal_session_property());
      break;
    }
    case kGetSessionProperty: {
      _internal_mutable_get_session_property()->::indiemotionpb::payloads::GetSessionPropertyByName::MergeFrom(from._internal_get_session_property());
      break;
    }
    case kInputDeviceXform: {
      _internal_mutable_input_device_xform()->::indiemotionpb::payloads::InputDeviceXForm::MergeFrom(from._internal_input_device_xform());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:indiemotionpb.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(header_, other->header_);
  swap(payload_, other->payload_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace indiemotionpb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::indiemotionpb::Header* Arena::CreateMaybeMessage< ::indiemotionpb::Header >(Arena* arena) {
  return Arena::CreateMessageInternal< ::indiemotionpb::Header >(arena);
}
template<> PROTOBUF_NOINLINE ::indiemotionpb::Message* Arena::CreateMaybeMessage< ::indiemotionpb::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::indiemotionpb::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
