// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indiemotion-proto/messages/cameras.proto

#include "indiemotion-proto/messages/cameras.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace indiemotion {
namespace messages {
constexpr ListCameras::ListCameras(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct ListCamerasDefaultTypeInternal {
  constexpr ListCamerasDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ListCamerasDefaultTypeInternal() {}
  union {
    ListCameras _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ListCamerasDefaultTypeInternal _ListCameras_default_instance_;
}  // namespace messages
}  // namespace indiemotion
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_indiemotion_2dproto_2fmessages_2fcameras_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_indiemotion_2dproto_2fmessages_2fcameras_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_indiemotion_2dproto_2fmessages_2fcameras_2eproto = nullptr;

const uint32_t TableStruct_indiemotion_2dproto_2fmessages_2fcameras_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::indiemotion::messages::ListCameras, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::indiemotion::messages::ListCameras)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::indiemotion::messages::_ListCameras_default_instance_),
};

const char descriptor_table_protodef_indiemotion_2dproto_2fmessages_2fcameras_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n(indiemotion-proto/messages/cameras.pro"
  "to\022\024indiemotion.messages\"\r\n\013ListCamerasb"
  "\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto = {
  false, false, 87, descriptor_table_protodef_indiemotion_2dproto_2fmessages_2fcameras_2eproto, "indiemotion-proto/messages/cameras.proto", 
  &descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_indiemotion_2dproto_2fmessages_2fcameras_2eproto::offsets,
  file_level_metadata_indiemotion_2dproto_2fmessages_2fcameras_2eproto, file_level_enum_descriptors_indiemotion_2dproto_2fmessages_2fcameras_2eproto, file_level_service_descriptors_indiemotion_2dproto_2fmessages_2fcameras_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto_getter() {
  return &descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_indiemotion_2dproto_2fmessages_2fcameras_2eproto(&descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto);
namespace indiemotion {
namespace messages {

// ===================================================================

class ListCameras::_Internal {
 public:
};

ListCameras::ListCameras(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:indiemotion.messages.ListCameras)
}
ListCameras::ListCameras(const ListCameras& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:indiemotion.messages.ListCameras)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListCameras::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListCameras::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ListCameras::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto_getter, &descriptor_table_indiemotion_2dproto_2fmessages_2fcameras_2eproto_once,
      file_level_metadata_indiemotion_2dproto_2fmessages_2fcameras_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace messages
}  // namespace indiemotion
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::indiemotion::messages::ListCameras* Arena::CreateMaybeMessage< ::indiemotion::messages::ListCameras >(Arena* arena) {
  return Arena::CreateMessageInternal< ::indiemotion::messages::ListCameras >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
